### ISSUE TITLE
关于model-n的核心板

### ISSUE THREAD

**Issue by Culturenotes** [PiCenter/QuarkNPi#3]
请问他改版后的model-n的核心板在哪里查看啊，我看稚晖大佬开源的都是之前的邮票孔的核心板，想学须一下

**Comment by Mehver** [comment]
我印象里model-n只开源了基板。毕竟m2接口的核心板让Seeed矽递量产了，淘宝上还是要卖钱的嘛。不过也可能将来会开源吧。有基板的资料你也可以自己做核心板。
